### ISSUE TITLE
Compilation error on macOS

### ISSUE THREAD

**Issue by anuragsoni** [janestreet/core_unix#2]
The current trunk of `core_unix` fails to compile on macOS as it attempts to use `clock_getcpuclockid` which is missing on macOS.

```
File "core_unix/src/dune", line 5, characters 45-65:
5 |  (c_names nss_stubs timespec core_unix_stubs core_unix_time_stubs)
                                                 ^^^^^^^^^^^^^^^^^^^^
core_unix_time_stubs.c:57:13: error: implicit declaration of function 'clock_getcpuclockid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  int ret = clock_getcpuclockid(pid, &clock);
            ^
```

macOS version: 12.2.1 (Monterey)

**Comment by anuragsoni** [comment]
One potential workaround is proposed at https://github.com/janestreet/jst-config/pull/4

**Comment by bcc32** [comment]
Does https://github.com/janestreet/jst-config/commit/e5fdac6e5df9ba93e014a4d2db841fdbf209446f fix this issue for you, @anuragsoni?
